# Server Configuration
server.port=8080

# OAuth Configuration

# TODO: Mask client id and secrets before pushing to Github
spring.security.oauth2.client.registration.gitlab.client-id=masked
spring.security.oauth2.client.registration.gitlab.client-secret=masked
spring.security.oauth2.client.registration.gitlab.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab.scope=openid
# 'code' in the url below signifies an endpoint locally that will receieve the authorization code
spring.security.oauth2.client.registration.gitlab.redirect-uri=http://localhost:8080/login/oauth2/code/gitlab


# Browser is redirected here to authenticate the user and get consent. Returns an authorization code to your redirect URI.
spring.security.oauth2.client.provider.gitlab.authorization-uri=https://gitlab.com/oauth/authorize
# Your backend calls this to exchange the authorization code for tokens (access/refresh), and later to refresh tokens. 
spring.security.oauth2.client.provider.gitlab.token-uri=https://gitlab.com/oauth/token
spring.security.oauth2.client.provider.gitlab.issuer-uri=https://gitlab.com
spring.security.oauth2.client.provider.gitlab.jwk-set-uri=https://gitlab.com/oauth/discovery/keys

