spring.application.name=eureka-server
server.port=8761

# Since it's a server, we don't want it to register with itself
eureka.client.register-with-eureka=false

# Also don't want the server to fetch the instances details from other servers
eureka.client.fetch-registry=false

# By default Server does not remove the client, even if heart beat is missed
# So we need to turn this OFF. And allow the server to remove if client heart beat missed
# Allowing server to remove the instance, if heart beat is not received
eureka.server.enable-self-preservation=false

# How frequently eviction task runs - how often server checks for dead instances (in milliseconds)
eureka.server.eviction-interval-timer-in-ms=6000
