spring.application.name=eureka-server
server.port=8762

# Hostname for this Eureka server instance
eureka.instance.hostname=localhost

# This Eureka server should register with other Eureka servers (peer1) to form a cluster
eureka.client.register-with-eureka=true

# This Eureka server should fetch registry from other Eureka servers to stay in sync
eureka.client.fetch-registry=true

# Point to peer1 (other Eureka server) - this forms the cluster
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# By default Server does not remove the client, even if heart beat is missed
# So we need to turn this OFF. And allow the server to remove if client heart beat missed
# Allowing server to remove the instance, if heart beat is not received
eureka.server.enable-self-preservation=false

# How frequently eviction task runs - how often server checks for dead instances (in milliseconds)
eureka.server.eviction-interval-timer-in-ms=6000

