server.port=8888

spring.cloud.config.server.git.uri=https://github.com/girikgarg8/centralconfig
spring.cloud.config.server.git.search-paths=global,order-service
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_ACCESS_TOKEN}
