spring.application.name=order-service

# This is OPTIONAL - tells that, getting the properties from config server is NON FATAL
# If config server is down or unreachable, we can still run the app using local properties
spring.cloud.config.fail-fast=false

# Config Server URL
spring.config.import=optional:configserver:http://localhost:8888

# Active profile (fetch dev profile from Config Server)
spring.profiles.active=dev

# Config for all profiles (dev, qa, prod etc)
custom.message=Hello from local default!

# ============================================
# ACTUATOR CONFIGURATION
# ============================================
# Expose refresh endpoint to allow refreshing configuration without restart
management.endpoints.web.exposure.include=refresh,health,info

# Show detailed health information
management.endpoint.health.show-details=always

