spring.application.name=apigateway
server.port=9090

# Path of the Eureka Server to fetch the microservices host details
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Route: Forward /products/** to product-service
# Now internally it will use Spring Cloud LoadBalancer framework to perform the load balancing
# - first it will fetch the instances from Service Discovery and
# - then it will use Spring Cloud load balancing algorithm to decide the routing
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**

# Route: Forward /orders/** to order-service
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://order-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**

