# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Define packages to scan
# It is optional, By default Spring boot looks for all @Entity, but still if we want specific package lookup
spring.jpa.packages-to-scan=com.girikgarg.learningspringboot

# Define Provider
# It is optional too, by default Spring boot automatically picks up

# the concerete class of JPA (Hibernate)
spring.jpa.properties.jakarta.persistence.provider=org.hibernate.jpa.HibernatePersistenceProvider
#the dialect (used to convert JPQL into SQL)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#transaction type, Default is RESOURCE_LOCAL (transaction local to one DB, not a distributed transaction)
spring.jpa.properties.jakarta.persistence.transactionType=RESOURCE_LOCAL

# Show SQL queries in console (optional, for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
