spring.application.name=learningspringboot
spring.datasource.url=jdbc:h2:mem:userDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.hibernate.javax.cache.missing_cache_strategy=create
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.cache.spi=DEBUG
logging.level.org.hibernate.stat=DEBUG

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

server.servlet.session.timeout=15m
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always


spring.security.oauth2.client.registration.gitlab.client-id=xx
spring.security.oauth2.client.registration.gitlab.client-secret=xx
spring.security.oauth2.client.registration.gitlab.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab.scope=openid
# 'code' in the url below signifies an endpoint locally that will receieve the authorization code
spring.security.oauth2.client.registration.gitlab.redirect-uri=http://localhost:8080/login/oauth2/code/gitlab

# Browser is redirected here to authenticate the user and get consent. Returns an authorization code to your redirect URI.
spring.security.oauth2.client.provider.gitlab.authorization-uri=https://gitlab.com/oauth/authorize
# Your backend calls this to exchange the authorization code for tokens (access/refresh), and later to refresh tokens. 
spring.security.oauth2.client.provider.gitlab.token-uri=https://gitlab.com/oauth/token
spring.security.oauth2.client.provider.gitlab.issuer-uri=https://gitlab.com
spring.security.oauth2.client.provider.gitlab.jwk-set-uri=https://gitlab.com/oauth/discovery/keys

