server.port=8083

spring.application.name=order-service

# Connect to multiple Eureka servers for high availability - if one goes down, client can still register with others
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/,http://localhost:8762/eureka/

# By-default values are true only, so we can even skip below configs
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# After this much seconds, client will send the new heart beat to server (Default time is 30sec)
eureka.instance.lease-renewal-interval-in-seconds=10

# Telling server to wait only this much time for the heart beat. After that, you can remove it from the list (Default time is 90sec)
eureka.instance.lease-expiration-duration-in-seconds=15
