# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:userDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL queries to observe L1 cache behavior
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate DDL auto (create tables automatically)
spring.jpa.hibernate.ddl-auto=create-drop
